global:
  namespace: votum-dev

nameOverride: votum-site-dev
fullnameOverride: ""

image:
  repository: nexus.k8s.corp.polygran.de/votum/votum-site-dev
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: votum.dev.polygran.io
  tls: []

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
